server:
  port: 8080

spring:
  application:
    name: rag-qa-system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

openai:
  api-key: sk-ws-H.REIRDPM.joDC.MEUCIQDpSRf21C6n7pX2nWVIa-_lN3MRGkZWPoQN83uHI1TRDQIgbY0_D4vgg9f0DzRnF9Vp0p3KHOf-iVfx6-ATB7lwq3I
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model:
    chat: qwen3.7-max-2026-05-20
    embedding: text-embedding-v4

# Qdrant 向量数据库配置
qdrant:
  host: localhost
  port: 6333        # REST API 端口
  collection: rag_documents

logging:
  level:
    com.ragqa: DEBUG
    dev.langchain4j: DEBUG